{
 "title": "VM Failure Details / Tenancy NMaaS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenancy",
    "query": "label_values(up{job=~\".*_ATL|.*_FRA\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Consul Servers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "consul_raft_peers{job=\"$consul\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "VM Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"passing\",job=\"$consul\"}>=1) by (status)",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "count(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1) by (status)",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "count(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1) by (status)",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "count(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"maintenance\",job=\"$consul\"}>=1) by (status)",
     "legendFormat": "{{ status}}"
    }
   ]
  },
  {
   "title": "VMs alive",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"passing\",job=\"$consul\"}>=1)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "VMs left",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "count(consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc|.*temp-repo-0|.*msosssnmpfm-0|.*msosssnmpfm-1\"} > 1 <4)"
    }
   ]
  },
  {
   "title": "VMs Failed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1)"
    },
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1)"
    },
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"maintenance\",job=\"$consul\"}>=1)"
    }
   ]
  },
  {
   "title": "Health Failed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1)"
    },
    {
     "expr": "sum(consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1)"
    },
    {
     "expr": "sum(consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"maintenance\",job=\"$consul\"}>=1)"
    }
   ]
  },
  {
   "title": "Members alive",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"passing\",job=\"$consul\"}>=1"
    }
   ]
  },
  { "title": "Members left", "type": "table", "gridPos": { "h": 7, "w": 8, "x": 7, "y": 12 } },
  {
   "title": "Members Failed ",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"maintenance\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"hadley\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"hadley\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"maintenance\",job=\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"hadley\",node=~\".+\",status=\"maintenance\",job=\"$consul\"}>=1"
    }
   ]
  },
  {
   "title": "VM Map",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"passing\",job=\"$consul\"}>=1)*0",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".+\",status=\"warning\",job=\"$consul\"}>=1)*1",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".+\",status=\"critical\",job=\"$consul\"}>=1)*2",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".+\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "content": "<h1>\n<p>\n\n\n</p>\n<center><a href=\"/d/lWQhHSxWz/vm-failure-history?orgId=1&var-consul=$consul\" target=\"_blank\">View History Events</a></center>\n<center><a href=\"/d/xtkCtBkiz/enm-gui-availability?orgId=1&refresh=10s\" target=\"_blank\">View ENM GUI Availability</a></center>\n<center><a href=\"/d/nxaK84qZk/cpu-memory?orgId=1&refresh=1m&var-consul=$consul\" target=\"_blank\">View Server Metrics History</a></center>\n<center><a href=\"/d/H08oIMWMk/application-metrics-history?var-consul=$consul&var-amos=All\" target=\"_blank\">View Application History Events</a></center>\n<center><a href=\"/d/BWO-uYGMz/all-application-dependencies?orgId=1\" target=\"_blank\">View All Application Dependencies</a></center>\n\n\n</h1>\n\n\n"
  }
 ]
}