{
 "title": "Overall Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenancy",
    "query": "label_values(up{job=~\".*_ATL|.*_FRA\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Server Failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (hostname)(cpu_usage_user{job=~\"$consul\"}>80  or cpu_usage_sys{job=~\"$consul\"}>80 or cpu_usage_wait{job=~\"$consul\"}>80 or cpu_usage_steal{job=~\"$consul\"}>80 or mem_used_percent{job=~\"$consul\"}>90))"
    }
   ]
  },
  {
   "title": "Total Consul Failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4))"
    }
   ]
  },
  {
   "title": "Total Application Failures",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0 or probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0 or (sum without (hostname)(pmserv_files_failed{job=~\"$consul\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\"})) >0.8) or (avg(pmserv_rop_collection_time{job=\"$consul\"}) >780) or (max(pmserv_rop_collection_time{job=\"$consul\"}) >890) or (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\"} <80) or (dp_total_number_of_hb_to_sas{job=~\"$consul\",hostname=~\".+dpmediation-0\"} == 0 and ON(job)(dp_total_number_of_hb_to_sas{job=~\"$consul\",hostname=~\".+dpmediation-1\"} ==0) and ON(job)(dp_grant_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_hb_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_spectrum_inquiry_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_relinquishment_requests_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_registration_requests_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0)) or (idelta(dp_failed_attempts_with_sas{job=~\"$consul\",hostname=~\".+dpmediation.*\"}[2m]) >0) or (idelta(dp_failed_connection_attempts_with_sas_incremental{job=~\"$consul\",hostname=~\".+domainproxy-0\"}[2m]) >0))"
    }
   ]
  },
  {
   "title": "Active HA Wfs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(ha_wfs_active{job=\"$consul\"})",
     "legendFormat": "HA"
    }
   ]
  },
  {
   "title": "Snapshot Workflow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count(snapshot_wfs_active{job=\"$consul\"})"
    }
   ]
  },
  {
   "title": "Upgrade Workflow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(upgrade_wfs_active{job=\"$consul\"})"
    }
   ]
  },
  {
   "title": "Backup Workflow",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "count(backup_wfs_active{job=\"$consul\"})",
     "legendFormat": "Backup"
    }
   ]
  },
  {
   "title": "VMs Alive",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"passing\",job=\"$consul\"}>=1)",
     "legendFormat": "VM Alive"
    }
   ]
  },
  {
   "title": "VMs Left",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4)"
    }
   ]
  },
  {
   "title": "VMs Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"critical|warning|maintenance\",job=\"$consul\"}>=1)"
    }
   ]
  },
  {
   "title": "Health Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1)"
    }
   ]
  },
  {
   "title": "Max Consumption in at least one of the VM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(mem_used_percent{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max(cpu_usage_user{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "User"
    },
    {
     "expr": "max(cpu_usage_sys{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "System"
    },
    {
     "expr": "max(cpu_usage_wait{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "IO Wait"
    },
    {
     "expr": "max(cpu_usage_steal{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "PM File Collection",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (hostname)(pmserv_files_failed{job=~\"$consul\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\"}))"
    }
   ]
  },
  {
   "title": "Avg ROP Collection Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(pmserv_rop_collection_time{job=\"$consul\"})",
     "legendFormat": "Avg ROP Collection Time"
    }
   ]
  },
  {
   "title": "Max ROP Collection Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pmserv_rop_collection_time{job=\"$consul\"})"
    }
   ]
  },
  {
   "title": "CM Synchronised Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "cm_status{type=\"sync_nodes\",tenancy=\"$consul\"}"
    }
   ]
  },
  {
   "title": "CM Supervised Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "cm_status{type=\"supervised_nodes\",tenancy=\"$consul\"}"
    }
   ]
  },
  {
   "title": "CM Sync",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 16 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "cm_status{type=\"sync_percent\",tenancy=\"$consul\"}"
    }
   ]
  },
  {
   "title": "ENM GUI",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 16 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"}"
    }
   ]
  },
  {
   "title": "ENM Login",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"}"
    }
   ]
  },
  {
   "title": "Server Failure List for selected Timerange",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max by (hostname,job) (mem_used_percent{job=~\"$consul\"}) >90"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_user{job=~\"$consul\"})>80"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_sys{job=~\"$consul\"})>80"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_wait{job=~\"$consul\"})>80"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_steal{job=~\"$consul\"})>80"
    }
   ]
  },
  {
   "title": "Consul Failure List for selected Timerange",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"critical\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"warning\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"maintenance\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"critical\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"warning\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"maintenance\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member!~\".*neo4j-cc\"} > 1 <4"
    }
   ]
  },
  {
   "title": "Application Failure List for selected Timerange",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0"
    },
    {
     "expr": "probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0"
    },
    {
     "expr": "sum without (hostname)(pmserv_files_failed{job=~\"$consul\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\"})) >0.8"
    },
    {
     "expr": "avg(pmserv_rop_collection_time{job=\"$consul\"}) >780"
    },
    {
     "expr": "max(pmserv_rop_collection_time{job=\"$consul\"}) >890"
    },
    {
     "expr": "cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\"} <80"
    },
    {
     "expr": "dp_total_number_of_hb_to_sas{job=~\"$consul\",hostname=~\".+dpmediation-0\"} == 0 and ON(job)(dp_total_number_of_hb_to_sas{job=~\"$consul\",hostname=~\".+dpmediation-1\"} ==0) and ON(job)(dp_grant_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_hb_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_spectrum_inquiry_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_relinquishment_requests_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_registration_requests_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0)"
    },
    {
     "expr": "idelta(dp_failed_attempts_with_sas{job=~\"$consul\",hostname=~\".+dpmediation.*\"}[2m]) >0"
    },
    {
     "expr": "idelta(dp_failed_connection_attempts_with_sas_incremental{job=~\"$consul\",hostname=~\".+domainproxy-0\"}[2m]) >0"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "content": "<h1>\n<p>\n\n\n</p>\n<center><a href=\"/d/lWQhHSxWz/vm-failure-history?orgId=1&var-consul=$consul\" target=\"_blank\">View History Events</a></center>\n\n<center><a href=\"/d/xtkCtBkiz/enm-gui-availability?orgId=1&refresh=10s\" target=\"_blank\">View ENM GUI Availability</a></center>\n\n<center><a href=\"/d/nxaK84qZk/cpu-memory?orgId=1&refresh=1m&var-consul=$consul\" target=\"_blank\">View Server Metrics History</a></center>\n<center><a href=\"/d/PX1MxgKMz/vnflcm-workflows?orgId=1&refresh=1m&from=now-6h&to=now&var-consul=$consul\" target=\"_blank\">VNFLCM Workflows History</a></center>\n<center><a href=\"/d/H08oIMWMk/application-metrics-history?var-consul=$consul&var-amos=All\" target=\"_blank\">View Application History Events</a></center>\n<center><a href=\"/d/BWO-uYGMz/all-application-dependencies?orgId=1\" target=\"_blank\">View All Application Dependencies</a></center>\n\n\n\n</h1>\n\n\n"
  }
 ]
}