{
 "title": "Overall VM Failures NMaaS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenancy",
    "query": "label_values(up{job=~\".*_ATL|.*_FRA\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Tenancies ATL",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (job) (up{job=~\".*_ATL\"}==1))"
    }
   ]
  },
  {
   "title": "Active Workflows",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "ha_wfs_active{job=~\"$consul\"} or snapshot_wfs_active{job=~\"$consul\"} or upgrade_wfs_active{job=~\"$consul\"} or backup_wfs_active{job=~\"$consul\"}"
    }
   ]
  },
  {
   "title": "Total Tenancies FRA",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (job) (up{job=~\".*_FRA\"}==1))"
    }
   ]
  },
  { "title": "VM Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "repeat": "consul",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "$consul",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(consul_health_node_status{check=~\"serfHealth|conhar\",node=~\".+\",status=~\"critical|warning|maintenance\",job=\"$consul\"}>=1 OR (consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc\"} > 1 <4) OR count by (hostname)(cpu_usage_user{job=~\"$consul+.*\"}>85  or pu_usage_sys{job=~\"$consul+.*\"}>85 or cpu_usage_wait{job=~\"$consul+.*\"}>85 or cpu_usage_steal{job=~\"$consul+.*\"}>85 or mem_used_percent{job=~\"$consul+.*\"}>98) OR (sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8) OR (avg(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >780) OR (max(pmserv_rop_collection_time{job=\"$consul\",job!=\"TRAILENM01_ATL\"}) >890) OR (cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50) OR (probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0) OR (probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0))"
    }
   ]
  },
  {
   "title": "Server Failure List for selected Timerange",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max by (hostname,job) (mem_used_percent{job=~\"$consul\"}) >98"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_user{job=~\"$consul\"})>85"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_sys{job=~\"$consul\"})>85"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_wait{job=~\"$consul\"})>85"
    },
    {
     "expr": "max by (hostname,job)  (cpu_usage_steal{job=~\"$consul\"})>85"
    }
   ]
  },
  {
   "title": "Consul Failure List for selected Timerange",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"critical\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"warning\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"serfHealth\",node=~\".+\",status=\"maintenance\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"critical\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"warning\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_health_node_status{check=\"conhar\",node=~\".+\",status=\"maintenance\",job=~\"$consul\"}>=1"
    },
    {
     "expr": "consul_serf_lan_member_status{job=\"$consul\",member!~\".*neo4j-cc|.*temp-repo-0|.*msosssnmpfm-0|.*msosssnmpfm-1\"} > 1 <4"
    }
   ]
  },
  {
   "title": "Application Failure List for selected Timerange",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_haproxy_availability\",tenancy=~\"$consul\"} == 0"
    },
    {
     "expr": "probe_success{job=\"blackbox_haproxy_login\",tenancy=~\"$consul\"} == 0"
    },
    {
     "expr": "sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\",job!=\"TRAILENM01_ATL\"})) >0.8"
    },
    {
     "expr": "avg(pmserv_rop_collection_time{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) >780"
    },
    {
     "expr": "max(pmserv_rop_collection_time{job=~\"$consul\",job!=\"TRAILENM01_ATL\"}) >890"
    },
    {
     "expr": "cm_status{exported_job=\"pushgateway\",job=\"pushgateway\",tenancy=~\"$consul\",type=\"sync_percent\",tenancy!~\"TRAILENM01_ATL|BMASENM01_ATL\"} <50"
    }
   ]
  }
 ]
}