{
 "title": "Application Metrics History",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenacy",
    "query": "label_values(up{job=~\".*_ATL|.*_FRA\"},job)"
   },
   {
    "name": "amos",
    "query": "label_values(amos_sessions{job=\"$consul\"},hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Amos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$amos",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "amos",
   "targets": [
    {
     "expr": "max(amos_sessions{hostname=~\"$amos\"})",
     "legendFormat": "AMOS Session"
    },
    {
     "expr": "max(amos_cpu_used{hostname=~\"$amos\"})",
     "legendFormat": "AMOS CPU Used %"
    },
    {
     "expr": "max(amos_mem_used{hostname=~\"$amos\"})",
     "legendFormat": "AMOS Mem Used %"
    }
   ]
  },
  {
   "title": "$amos",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(amos_sessions{hostname=~\"$amos\"})",
     "legendFormat": "AMOS Session"
    },
    {
     "expr": "max(amos_cpu_used{hostname=~\"$amos\"})",
     "legendFormat": "AMOS CPU Used %"
    },
    {
     "expr": "max(amos_mem_used{hostname=~\"$amos\"})",
     "legendFormat": "AMOS Mem Used %"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (amos_sessions{job=\"$consul\", hostname=~\".*\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "$amos CPU/MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "amos",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(amos_cpu_used{hostname=\"$amos\"})",
     "legendFormat": "CPU Used "
    },
    {
     "expr": "max(amos_mem_used{hostname=\"$amos\"})",
     "legendFormat": "Mem Used "
    }
   ]
  },
  {
   "title": "$amos CPU/MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(amos_cpu_used{hostname=\"$amos\"})",
     "legendFormat": "CPU Used "
    },
    {
     "expr": "max(amos_mem_used{hostname=\"$amos\"})",
     "legendFormat": "Mem Used "
    }
   ]
  },
  { "title": "PM KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "PM File Collection",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (hostname)(pmserv_files_failed{job=~\"$consul\"}) / (sum without (hostname)(pmserv_files_collected{job=~\"$consul\"})+sum without (hostname)(pmserv_files_failed{job=~\"$consul\"}))"
    }
   ]
  },
  {
   "title": "Max File Collected",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum without (hostname) (pmserv_files_collected{job=\"$consul\"})"
    }
   ]
  },
  {
   "title": "Files collected vs Max Files collected over 6h",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum without (hostname) (pmserv_files_collected{job=~\"$consul\"}) / ignoring(hostname) ((max_over_time(pmserv_files_collected{job=~\"$consul\",hostname=~\".*pmserv-0\"}[6h])  ) + ignoring(hostname) (max_over_time(pmserv_files_collected{job=~\"$consul\",hostname=~\".*pmserv-1\"}[6h]))))*100"
    }
   ]
  },
  {
   "title": "Avg ROP Collection Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(pmserv_rop_collection_time{job=\"$consul\"})",
     "legendFormat": "Avg ROP Collection Time"
    }
   ]
  },
  {
   "title": "Max ROP Collection Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pmserv_rop_collection_time{job=\"$consul\"})"
    }
   ]
  },
  {
   "title": "PM File Collection Analysis",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (hostname) (pmserv_files_collected{job=\"$consul\"})",
     "legendFormat": "File Collection"
    },
    {
     "expr": "sum without (hostname) (pmserv_files_failed{job=\"$consul\"})",
     "legendFormat": "File Failed"
    }
   ]
  },
  {
   "title": "PM ROP Collection Time Analysis",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pmserv_rop_collection_time{job=\"$consul\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "CM KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Synchronised Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cm_status{type=\"sync_nodes\",tenancy=\"$consul\"}"
    }
   ]
  },
  {
   "title": "Supervised Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cm_status{type=\"supervised_nodes\",tenancy=\"$consul\"}"
    }
   ]
  },
  {
   "title": "CM Sync Percent",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "cm_status{type=\"sync_percent\",tenancy=\"$consul\"}"
    }
   ]
  },
  {
   "title": "CM Nodes Analysis",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cm_status{type=\"sync_nodes\",tenancy=\"$consul\"}",
     "legendFormat": "Synchroinised Nodes"
    },
    {
     "expr": "cm_status{type=\"supervised_nodes\",tenancy=\"$consul\"}",
     "legendFormat": "Supervised Nodes"
    }
   ]
  },
  {
   "title": "CM Sync Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cm_status{type=\"sync_percent\",tenancy=\"$consul\"}",
     "legendFormat": "Sync percent"
    }
   ]
  },
  {
   "title": "Domain Coordinator & Domain Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Domain Coordinator Service Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "count(dp_total_number_of_hb_to_sas{job=~\"$consul\",hostname=~\".+dpmediation-0\"} == 0 and ON(job)(dp_total_number_of_hb_to_sas{job=~\"$consul\",hostname=~\".+dpmediation-1\"} ==0) and ON(job)(dp_grant_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_hb_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_spectrum_inquiry_request_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_relinquishment_requests_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0) and ON(job)(dp_registration_requests_count{job=~\"$consul\",hostname=~\".+domainproxy-0\"} ==0))"
    }
   ]
  },
  {
   "title": "Domain Coordinator Service Status Analysis",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dp_total_number_of_hb_to_sas{job=\"$consul\",hostname=~\".+dpmediation-0\"}",
     "legendFormat": "TotalNumberOfHbToSAS dpmediation-0"
    },
    {
     "expr": "dp_total_number_of_hb_to_sas{job=\"$consul\",hostname=~\".+dpmediation-1\"}",
     "legendFormat": "TotalNumberOfHbToSAS dpmediation-1"
    },
    {
     "expr": "dp_grant_request_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "GrantRequestsCount domainproxy-0"
    },
    {
     "expr": "dp_hb_request_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "HeartbeatRequestsCount domainproxy-0"
    },
    {
     "expr": "dp_spectrum_inquiry_request_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "SpectrumInquiryRequestsCount domainproxy-0"
    },
    {
     "expr": "dp_relinquishment_requests_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "RelinquishmentRequestsCount domainproxy-0"
    },
    {
     "expr": "dp_registration_requests_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "RegistrationRequestsCount domainproxy-0 "
    }
   ]
  },
  {
   "title": "SAS Connectivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "idelta(dp_failed_attempts_with_sas{job=~\"$consul\",hostname=~\".+dpmediation.*\"}[2m])",
     "legendFormat": "{{ hostname }}"
    },
    {
     "expr": "idelta(dp_failed_connection_attempts_with_sas_incremental{job=~\"$consul\",hostname=~\".+domainproxy-0\"}[2m])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "SAS Connectivity Analysis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dp_failed_attempts_with_sas{job=~\"$consul\",hostname=~\".+dpmediation.*\"}",
     "legendFormat": "{{ hostname }}"
    },
    {
     "expr": "idelta(dp_failed_connection_attempts_with_sas_incremental{job=~\"$consul\",hostname=~\".+domainproxy-0\"}[2m]) ",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Domain Proxy Cells Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dp_active_cells_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "Domain  Proxy Active Cells Count"
    },
    {
     "expr": "dp_inactive_cells_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "Domain  Proxy Inactive Cells Count"
    },
    {
     "expr": "dp_maintained_grants_count{job=\"$consul\",hostname=~\".+domainproxy-0\"}",
     "legendFormat": "Domain  Proxy Maintained Grants Cells Count"
    }
   ]
  }
 ]
}