{
 "title": "All Application Dependencies",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenancy",
    "query": "label_values(up{job=~\".*_ATL|.*FRA\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "PM Application",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*|.*pmserv.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*|.*pmserv.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*|.*pmserv.*\",status=\"warning\",job=~\"$consul\"}>=1)*1",
     "legendFormat": "{{ node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*|.*pmserv.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "PM Router Transport nodes",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*jms.*|.*nfspmlink.*|.*nfspm.*|.*nfscommon.*|.*haproxy.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "CM CLI",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*jms.*|.*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*cmserv.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*jms.*|.*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*cmserv.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*jms.*|.*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*cmserv.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*jms.*|.*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*cmserv.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "SHM Application",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*jms.*|.*postgres.*|.*nfssmrs.*|.*haproxy.*|.*shmcoreserv.*|.*shmserv.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*postgres.*|.*nfssmrs.*|.*haproxy.*|.*shmcoreserv.*|.*shmserv.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*postgres.*|.*nfssmrs.*|.*haproxy.*|.*shmcoreserv.*|.*shmserv.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*jms.*|.*postgres.*|.*nfssmrs.*|.*haproxy.*|.*shmcoreserv.*|.*shmserv.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "FMNBI",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*jms.*|.*visinamingnb.*|.*haproxy.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*jms.*|.*visinamingnb.*|.*haproxy.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*jms.*|.*visinamingnb.*|.*haproxy.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*jms.*|.*visinamingnb.*|.*haproxy.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "NETEX",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*netex.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*netex.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*netex.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*netex.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "CM Bulk Import Live",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*postgres.*|.*jms.*|.*solr.*|.*elasticsearch.*|.*openidm.*|.*nfsmdt.*|.*nfsconfigmgt.*|.*haproxy.*|.*impexp.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*postgres.*|.*jms.*|.*solr.*|.*elasticsearch.*|.*openidm.*|.*nfsmdt.*|.*nfsconfigmgt.*|.*haproxy.*|.*impexp.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*postgres.*|.*jms.*|.*solr.*|.*elasticsearch.*|.*openidm.*|.*nfsmdt.*|.*nfsconfigmgt.*|.*haproxy.*|.*impexp.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*postgres.*|.*jms.*|.*solr.*|.*elasticsearch.*|.*openidm.*|.*nfsmdt.*|.*nfsconfigmgt.*|.*haproxy.*|.*impexp.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "FM Applications",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*jms.*|.*solr.*|.*nfsmdt.*|.*haproxy.*|.*fmserv.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*solr.*|.*nfsmdt.*|.*haproxy.*|.*fmserv.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*jms.*|.*solr.*|.*nfsmdt.*|.*haproxy.*|.*fmserv.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*jms.*|.*solr.*|.*nfsmdt.*|.*haproxy.*|.*fmserv.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "CM Bulk Export",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*neo4j.*|.*postgres.*|.*nfsbatch.*|.*nfscommon.*|.*haproxy.*|.*impexp.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*postgres.*|.*nfsbatch.*|.*nfscommon.*|.*haproxy.*|.*impexp.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*neo4j.*|.*postgres.*|.*nfsbatch.*|.*nfscommon.*|.*haproxy.*|.*impexp.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*neo4j.*|.*postgres.*|.*nfsbatch.*|.*nfscommon.*|.*haproxy.*|.*impexp.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "AMOS",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*amos.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*amos.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*postgres.*|.*nfscommon.*|.*nfsnrbk.*|.*haproxy.*|.*amos.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "User Management",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*postgres.*|.*jms.*|.*openidm.*|.*nfscommon.*|.*haproxy.*|.*accesscontrol.*|.*secserv.*|.*sso.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*postgres.*|.*jms.*|.*openidm.*|.*nfscommon.*|.*haproxy.*|.*accesscontrol.*|.*secserv.*|.*sso.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*postgres.*|.*jms.*|.*openidm.*|.*nfscommon.*|.*haproxy.*|.*accesscontrol.*|.*secserv.*|.*sso.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*postgres.*|.*jms.*|.*openidm.*|.*nfscommon.*|.*haproxy.*|.*accesscontrol.*|.*secserv.*|.*sso.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "ESM",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*esmon.*|.*haproxy.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*esmon.*|.*haproxy.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*esmon.*|.*haproxy.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*esmon.*|.*haproxy.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Infrastructure Applications",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "(consul_health_node_status{check=\"conhar\",node=~\".*postgres.*|.*repo.*|.*emp.*|.*vaultserv.*|.*servicereg.*|.*opendj.*|.*esmon.*|.*elasticsearch.*|.*jms.*|.*models.*|.*solr.*|.*neo4j.*|.*sps.*|.*nfscommon.*|.*nfspm.*|.*nfssmrs.*|.*haproxy.*\",status=\"passing\",job=\"$consul\"}>=1)*0 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*postgres.*|.*repo.*|.*emp.*|.*vaultserv.*|.*servicereg.*|.*opendj.*|.*esmon.*|.*elasticsearch.*|.*jms.*|.*models.*|.*solr.*|.*neo4j.*|.*sps.*|.*nfscommon.*|.*nfspm.*|.*nfssmrs.*|.*haproxy.*\",status=\"critical\",job=~\"$consul\"}>=1)*2 or (consul_health_node_status{check=~\"conhar|serfHealth\",node=~\".*postgres.*|.*repo.*|.*emp.*|.*vaultserv.*|.*servicereg.*|.*opendj.*|.*esmon.*|.*elasticsearch.*|.*jms.*|.*models.*|.*solr.*|.*neo4j.*|.*sps.*|.*nfscommon.*|.*nfspm.*|.*nfssmrs.*|.*haproxy.*\",status=\"warning\",job=~\"$consul\"}>=1)*1 ",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(consul_serf_lan_member_status{instance=~\".+\",job=~\"$consul\",member=~\".*postgres.*|.*repo.*|.*emp.*|.*vaultserv.*|.*servicereg.*|.*opendj.*|.*esmon.*|.*elasticsearch.*|.*jms.*|.*models.*|.*solr.*|.*neo4j.*|.*sps.*|.*nfscommon.*|.*nfspm.*|.*nfssmrs.*|.*haproxy.*\"} > 1 <4)*3",
     "legendFormat": "{{member}}"
    }
   ]
  }
 ]
}