{
 "title": "Server Metrics / Tenancy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenancy",
    "query": "label_values(up{job=~\".*_ATL|.*_FRA\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max Memory Consumption in at least one of the VM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(mem_used_percent{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Max CPU Consumption in at least one of the VM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "max(cpu_usage_user{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "User"
    },
    {
     "expr": "max(cpu_usage_sys{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "System"
    },
    {
     "expr": "max(cpu_usage_wait{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "IO Wait"
    },
    {
     "expr": "max(cpu_usage_steal{hostname=~\".+\",job=~\"$consul\"})",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "Max Consumptions | CPU > 85 | Memory >98",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (hostname)  (mem_used_percent{job=~\"$consul\"})>98",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max by (hostname)  (cpu_usage_user{job=~\"$consul\"})>85",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max by (hostname)  (cpu_usage_sys{job=~\"$consul\"})>85",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max by (hostname)  (cpu_usage_wait{job=~\"$consul\"})>85",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "max by (hostname)  (cpu_usage_steal{job=~\"$consul\"})>85",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "content": "<h1>\n<p>\n\n\n</p>\n<center><a href=\"/d/lWQhHSxWz/vm-failure-history?orgId=1&var-consul=$consul\" target=\"_blank\">View History Events</a></center>\n\n<center><a href=\"/d/xtkCtBkiz/enm-gui-availability?orgId=1&refresh=10s\" target=\"_blank\">View ENM GUI Availability</a></center>\n\n<center><a href=\"/d/nxaK84qZk/cpu-memory?orgId=1&refresh=1m&var-consul=$consul\" target=\"_blank\">View Server Metrics History</a></center>\n<center><a href=\"/d/PX1MxgKMz/vnflcm-workflows?orgId=1&refresh=1m&from=now-6h&to=now&var-consul=$consul\" target=\"_blank\">VNFLCM Workflows History</a></center>\n<center><a href=\"/d/H08oIMWMk/application-metrics-history?var-consul=$consul&var-amos=All\" target=\"_blank\">View Application History Events</a></center>\n<center><a href=\"/d/BWO-uYGMz/all-application-dependencies?orgId=1\" target=\"_blank\">View All Application Dependencies</a></center>\n\n\n\n</h1>\n\n\n"
  }
 ]
}