{
 "title": "Server Metrics / VM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Tenancy",
    "query": "label_values(up{job=~\".*_ATL|.*_FRA\"},job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(cpu_usage_steal{job=~\"$consul\"},hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(mem_used_percent{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "max(cpu_usage_user{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "User"
    },
    {
     "expr": "max(cpu_usage_sys{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "System"
    },
    {
     "expr": "max(cpu_usage_wait{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "IO Wait"
    },
    {
     "expr": "max(cpu_usage_steal{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "Steal"
    }
   ]
  },
  { "title": "CPU Max Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Max Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(cpu_usage_steal{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "steal"
    },
    {
     "expr": "max(cpu_usage_wait{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "wait"
    },
    {
     "expr": "max(cpu_usage_user{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "user"
    },
    {
     "expr": "max(cpu_usage_sys{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "system"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(mem_used_percent{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Memory Used (VS) Memory Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "max(mem_free_kb{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "max(mem_used_kb{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  { "title": "JBOSS CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "JVM CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(cpu_process_cpu_load{hostname=~\"$hostname\",job=~\"$consul\"}) ",
     "legendFormat": "JVM CPU Load"
    }
   ]
  },
  {
   "title": "JVM Memory Committed / Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(jvm_memory_heap_memory_usage_committed{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "max(jvm_memory_heap_memory_usage_used{hostname=~\"$hostname\",job=~\"$consul\"})",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network packets / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_rx_packets{job=~\"$consul\", hostname=~\"$hostname\"}",
     "legendFormat": "{{interface}} - RX"
    },
    {
     "expr": "network_tx_packets{job=~\"$consul\", hostname=~\"$hostname\", interface=~\".*\"}",
     "legendFormat": "{{interface}} - TX"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "(network_rx_kb{job=~\"$consul\", hostname=~\"$hostname\", interface=~\".*\"})",
     "legendFormat": "{{interface}} - RX"
    },
    {
     "expr": "(network_tx_kb{job=~\"$consul\", hostname=~\"$hostname\", interface=~\".*\"})",
     "legendFormat": "{{interface}} - TX"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Storage Util Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(storage_utils_percent{job=~\"$consul\", hostname=~\"$hostname\", device=~\".*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Storage transaction seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(storage_transaction_seconds{job=~\"$consul\", hostname=~\"$hostname\", device=~\".*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Storage write seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(storage_write_seconds{job=~\"$consul\", hostname=~\"$hostname\", device=~\".*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Storage Read seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(storage_read_seconds{job=~\"$consul\", hostname=~\"$hostname\", device=~\".*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Storage Await",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(storage_await{job=~\"$consul\", hostname=~\"$hostname\", device=~\".*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Storage Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(storage_queue{job=~\"$consul\", hostname=~\"$hostname\", device=~\".*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Top CPU / Memory consuming processes for AMOS/SCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }
  },
  {
   "title": "Top CPU Consuming Process (Instant)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "top_cpu_process{job=\"$consul\",hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Top Memory Consuming Process (Instant)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "top_mem_process{job=\"$consul\",hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Top CPU Consuming Process > 15%",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "top_cpu_process{job=\"$consul\",hostname=\"$hostname\"} > 15",
     "legendFormat": "{{ command }} - {{ pid }}"
    }
   ]
  },
  {
   "title": "Top Memory Consuming Process > 5%",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "top_mem_process{job=\"$consul\",hostname=\"$hostname\"} > 5",
     "legendFormat": "{{ command }} - {{ pid }}"
    }
   ]
  }
 ]
}